spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER_URI}
          jwk-set-uri: ${OKTA_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.polyrepo: DEBUG

polyrepo:
  security:
    cors:
      allowed-origins:
        - ${FRONTEND_URL:https://*.okteto.dev}
